### ISSUE TITLE
demo已经失效了的说

### ISSUE THREAD

**Issue by jiehua1995** [Seevil/fantasy#12]
demo已经失效了的说
现在是类似Cactus的那种主题。
[blog](https://jiehua1995.github.io/Blog/)
其实我也喜欢Cactus~~

**Comment by Seevil** [comment]
哈，因为我换主题了，https://www.xde.io/typecho/fantasy.html 你可以看下这个里面又截图。fantasy 也挺很好看的，就算评论那快还是有的瑕疵

**Comment by jiehua1995** [comment]
哈哈好哒~~
