### ISSUE TITLE
在“分类”下的文章数量不能全部显示

### ISSUE THREAD

**Issue by yannisme** [Seevil/fantasy#15]
嘤嘤嘤，发现个小BUG，不知道是不是~🙃
在“分类”下的文章数量不能全部显示，显示的数量被设置中的阅读设置的“每页文章数目”所限制住

**Comment by Seevil** [comment]
有截图吗？

**Comment by yannisme** [comment]
![image.png](https://i.loli.net/2020/11/24/eag9pLNUt3H8oni.png)

![image.png](https://i.loli.net/2020/11/24/wDPe1qBnJUMOIrx.png)

以下是更改到10篇的数量：（仙人掌和Fantasy好像都存在这样的问题）

![image.png](https://i.loli.net/2020/11/24/C7RFYwE6Ag4sqda.png)

![image.png](https://i.loli.net/2020/11/24/ield6b2nBDZ3cL8.png)

**Comment by Seevil** [comment]
emmmm... 就是这样的啊你后台设置多少就显示多少（除了这个还有评论、分页、首页文章数啥的（首页有时主题开发时会设置固定显示数例如仙人掌）都受后台设置约束），要想全部显示一般都是归档页才会这样处理

**Comment by Seevil** [comment]
> emmmm ...就是这样的啊你的后台设置多少就显示了多少（除了这个还有评论，分页，首页文章数啥的（有时情况主题开发时会设置固定显示数仙人掌）都受后台设置约束）要想全部显示一般都是缩减页才会这样处理

这个可能是个bug 分类列表页没有做分页处理，后面我看下有空更新一下
